[project]
name = "ans-main-tg-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.15.0",
    "asyncpg>=0.30.0",
    "pydantic-settings>=2.7.0",
    "pydantic>=2.9.2",
]
